name: Scrape latest sdn dataset

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 40 */1 * * *

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -o sdn.csv https://www.treasury.gov/ofac/downloads/sdn.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest sdn data: ${timestamp}" || exit 0
        git push
